---
driver:
  name: dokken
  privileged: true
  chef_version: latest
  binds:
    - <%= File.expand_path('.') %>:/tmp/staging

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec
  root_path: /opt/verifier
  sudo: false
  inspec_tests:
    - test/integration/default

platforms:
  - name: ubuntu
    driver:
      image: ubuntu:16.04
      intermediate_instructions:
        - RUN apt-get update
        - RUN apt-get -y install systemd iproute2
      pid_one_command: /lib/systemd/systemd

suites:
  - name: sensu-latest
    run_list:
      - recipe[test]
    attributes:
      staging_dir: /tmp/staging
      build_dir: /tmp/build
  - name: sensu-0.29
    run_list:
      - recipe[test]
    attributes:
      staging_dir: /tmp/staging
      build_dir: /tmp/build
      sensu_version: 0.29.0-11
