language: ruby
dist: xenial

branches:
  only:
    - master

sudo: required

addons:
  apt:
    sources:
      - sourceline: deb https://packages.chef.io/repos/apt/current xenial main
        key_url: https://packages.chef.io/chef.asc
    packages:
      - chefdk

services:
  - docker

before_install:
  - gem install bundler
  - chef exec gem install bundler

env:
  global:
    - secure: PZwdJ18KpFLqDej/Kc0dV1Zdc0gRwbEowwypl/tGL7SzuWFSrhA09DSk63O7HpZaLfIkAvI+z2Og+zd49i6rDo1LP+N7rNJ3vnpu8/iS/SvdIh80iOIqdwKEAqGuSv/mMfj9Q1u71t/qQ6yra6pUvMUNJxOlay4sbsg+PBQbFLdFJKWqjeusTG9ZRH/597RHleaFQ3/6Vx2u0Ui3rooCTX1YMWA5kgRc55FscCL8oKzTSrKNbNbjG36xgOsx3Zx8Tr96kFv/ZUaSipNlHQOCfSvzccRMRZiPdp4QCnJQ0l6bgebxQRRnrcHxMrhxggKkp9VQmNFWlWsInerPI9LigD5lEGWe7RzUicrcuAsavqj1ZSUiT5QT8meMsibz5iSfdXKtquwj/X1/U8yTIcP8OSL9rOlupgA5AM/ONLekJ4Y8RCTGplyd+JryQtsnCjx4KPhb+Z2G10I8x3/wOeglMyryxXJ6lPS8ENrEoWj7cze381PWrgnedkQWsyvBw8bXWAS5NCofiS0zlRGyvPJb2TiYkuXOwFmzV6orc3KZmjBdzEQy5Nhxif3p+G99YO8uaNqX0Bhtr+q7ee+MxwqqJvmsKhMXGdUaYQ0EyWaLClChCt8tZa+i1+zHQCWSOFZbw894pOOFZAVAqN/qfJ4jmAZM0TsEVThnCHvJ04bPyB0=
  matrix:
    - SUITE=unit
    - SUITE=default

script:
  - if test "$SUITE" = "unit"; then bundle exec rake; fi
  - if test "$SUITE" != "unit"; then chef exec kitchen test $SUITE; fi

stages:
  - name: test
  - name: deploy
    if: NOT type = cron AND branch = master

jobs:
  include:
    - stage: deploy
      install: skip
      env:
        - VERSION=`ruby -e 'print Gem::Specification.load("sensu-plugins-habitat.gemspec").version'`
      script: skip
      before_deploy:
        - test -d bonsai || git clone https://github.com/sensu/sensu-go-bonsai-asset bonsai
        - git remote set-url origin "https://${GITHUB_TOKEN}@github.com/socrata-platform/sensu-plugins-habitat"
      deploy:
        - provider: script
          script: git tag -a v${VERSION} -m "Tagging v${VERSION} for release" && git push --tags
        - provider: script
          script: TRAVIS_TAG="v${VERSION}" bonsai/ruby-runtime/travis-build-ruby-plugin-assets.sh sensu-plugins-habitat
        - provider: rubygems
          api_key:
            secure: F0+VKSbFkSa3/Qgbfn3ueaTRQDH5mEjkcXYl9vI6nSbUIJoozNHfwXjDbG9u4GSgmGOygC93YO6v5L6NUuM7Ngd4IfCycpConS8YMIM2xCO+QpeQq2HRlBbfgcnLd8JOf8GgiC1tmTP75vlai5i16SgE6Fki0Tea4JF4T7JmNPQObB5U0F9orB+bil6l2FTdJvgB420shP7kM89Sywe7gaUE6+EPTqEZOtURSZVcy14VDgG2ZqcNDjhWpangrQGjzucqP4yjsZ8uDY56XrSFXYdizDIBOG+/BIK8o3H4FIk2Z0Cu3s+cT/ub4ZIuC/IIA/OM/ONsn/WZVWq5O5kuxSNiRb5hLo9N8+nHlIYcapB31V1jQeFFWjiG0b8Sz1nKiRsO7tZ+SfNdGFOc6cJzDEI2qkCbKGVzFLvjqLlq1GcZwZnXfMbgKYNr9M/6UwsBEKTuvRc6SvJnptrHcy9U+U5PZhY8Fyd2fxqhW5UJO2t/6Bvc3CArnKp+xrnfUjh22fDgXx2gwLbLIgbNSFQAZ2+Zi2JBuP8XorIGBP947sDAf4B7pGTN22aE/aRTAZPs0ylsNW3bNN2O3v0Kw+FJhYzlryO25jqrP+v0ynEYMBM1FPXnFHKPovZVVSjx5sKh/pyAw3F1AtaTi6DIOX/W0dMytSrYUh5WQD0WHfXBKPE=

notifications:
  slack:
    on_failure: change
    on_success: never
    on_pull_requests: false
    rooms:
      - secure: Rqnsw1wEcwMhEFzOedfZeBctGkxCsdbWJEGzY1O6DYn6tJhD5GTnbxjF4S71qLvfM1fnyuu6CySGkENMTJnveP1G4+j2rErcPUVI6PzMJ+nxQgT2+kuOlAL45H4zeYM5Jj8+hnUeid+UqQUacELgeyBDBkGOvRAfMxYjZHlGuujdjXGibKlCVasqhA7wO59VVs+Ao0DMYLwSOxBtzKgrJoZDw3Cr6cAEehDlyzK8Qu+e2zFfJQb12Ie4cpsDx2mLWFZAB/FOmP83bdSf3lx5gxq2a/YP4HOLLFb0JF/BnRMnwg6ToTQhbSswVoRGsVTgtRytv15rLV/KEYNP6WrOSnL81ZDrTkZTfBSmwq8qSR65I+HWlNzg8a53gbVWjonrVmZ+deIFe+wouUhoCyEIhlaBbhLWNNaORHveIqOOC8p3o5flCIx904KEgGhxyDyoLjdrAMSTu0sWu1HCf/tEghmNEAdIgm+HsXflTJNqJqmR1cCEmNLho/Y/MBk2cCNNKPYt4007aVMDJkOcRYVvaHicP9nkRsH0/Dkw5WVogTxC1PTMmEuoWisMKKOqmTt+j+SqU6yxGg6KC/ZufWhCWVl+1B8rAdPkXBXEw5gAkzB1r2Qr1G4yGKryYi+dQvLUVn6kKa1IB3ztdzvrX7R454Kuzdma9eaJYWhdiWyxBOs=
